---
version: '3.7'

services:
  besu:
    restart: ${CONTAINER_RESTART-on-failure}
    networks:
      - orchestrate
    image: hyperledger/besu:latest
    command: "--config-file=/config/config.toml"
    ports:
      - 8545:8545
    volumes:
      - ./config/besu/networkFiles/orchestrate/config.toml:/config/config.toml
      - ./config/besu/networkFiles/orchestrate/genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/orchestrate/key:/config/key
volumes:
  besu:
    driver: local
networks:
  orchestrate:
    external:
      name: deps_orchestrate
