---
version: '3.6'

x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: quorumengineering/quorum:${QUORUM_VERSION:-2.7.0}
  expose:
    - 30303
    - 8545
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  entrypoint: >
    /bin/sh -c
    "
    mkdir /data;
    cp -r /quorum/* /data;
    geth --datadir=/data init /config/genesis.json;
    cp /config/keys/accountkey /data/keystore/key;
    cp /config/keys/nodekey /data/geth/nodekey;

    geth
    --datadir /data
    --nodiscover
    --permissioned
    --verbosity 5
    --istanbul.blockperiod 5 --mine --minerthreads 1 --emitcheckpoints
    --syncmode full --nousb
    --networkid ${QUORUM_NETWORK_ID:-10}
    --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONS_ALGO:-istanbul}
    --port 30303
    --identity node${NODE_ID}-${QUORUM_CONS_ALGO:-istanbul}
    --password /config/passwords.txt ;
    "

services:

  validator1:
    << : *quorum-def
    ports:
      - 22000:8545/tcp
      - 30303
    environment:
      - NODE_ID=1
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator1:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.11

  validator2:
    << : *quorum-def
    ports:
      - 22001:8545/tcp
      - 30303
    environment:
      - NODE_ID=2
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator2:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.12

  validator3:
    << : *quorum-def
    ports:
      - 22002:8545/tcp
      - 30303
    environment:
      - NODE_ID=3
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator3:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.13

  validator4:
    << : *quorum-def
    ports:
      - 22003:8545/tcp
      - 30303
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator4:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.14

  rpcnode:
    << : *quorum-def
    ports:
      - 8545:8545/tcp
      - 30303
    environment:
      - NODE_ID=5
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/rpcnode:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.15

  explorer:
    build: images/block-explorer-light
    image: quorum-dev-quickstart/block-explorer-light:${QUORUM_VERSION}
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.30

networks:
  quorum-examples-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:

  "cakeshopvol":
