version: '3.7'

x-default-variables: &default-variables
  LOG_LEVEL: ${LOG_LEVEL-INFO}
  LOG_FORMAT: ${LOG_FORMAT-text}
  HTTP_PORT: ${HTTP_PORT-8080}
  HTTP_HOST: ${HTTP_HOST-0.0.0.0}
  HEALTH_PORT: ${HEALTH_PORT-8081}
  DB_TLS_SSLMODE: ${DB_TLS_SSLMODE-disable}
  DB_TLS_CERT: ${DB_TLS_CERT-}
  DB_TLS_KEY: ${DB_TLS_KEY-}
  DB_TLS_CA: ${DB_TLS_CA-}
  DB_HOST: ${DB_HOST-postgres}
  DB_PORT: ${DB_PORT-}
  DB_DATABASE: ${DB_DATABASE-}
  DB_POOLSIZE: ${DB_POOLSIZE-}
  DB_POOL_TIMEOUT: ${DB_POOL_TIMEOUT-}
  AUTH_OIDC_CA_CERT: ${AUTH_OIDC_CA_CERT-}
  AUTH_OIDC_ISSUER_URL: ${AUTH_OIDC_ISSUER_URL-}
  HTTPS_ENABLED: ${HTTPS_ENABLED-}
  HTTPS_SERVER_KEY: ${HTTPS_SERVER_KEY-}
  HTTPS_SERVER_CERT: ${HTTPS_SERVER_CERT-}
  AUTH_TLS_CA: ${AUTH_TLS_CA-}
  AUTH_API_KEY_FILE: ${AUTH_API_KEY_FILE-}

x-container-common: &container-common
  restart: ${CONTAINER_RESTART-on-failure}
  networks:
  - deps
  - qkm

services:
  key-manager-migration:
    <<: *container-common
    image: consensys/quorum-key-manager:v21.12.1
    environment:
      <<: *default-variables
    command: migrate up

  key-manager:
    <<: *container-common
    image: consensys/quorum-key-manager:v21.12.1
    environment:
      <<: *default-variables
      MANIFEST_PATH: ${MANIFEST_PATH-/manifests}
    ports:
    - 8080:8080
    - 8081:8081
    depends_on:
    - key-manager-migration
    command: run
    volumes:
    - ${HOST_MANIFEST_PATH-./manifests}:/manifests:ro

networks:
  qkm:
    name: qkm_quorum-dev-quickstart
  deps:
    external:
      name: deps_quorum-dev-quickstart
