version: '3.7'

x-container-common: &container-common
  restart: ${CONTAINER_RESTART-on-failure}
  networks:
  - deps

services:
  vault:
    <<: *container-common
    image: consensys/quorum-hashicorp-vault-plugin:v1.1.4
    tty: true
    restart: "no"
    cap_add:
    - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN-DevVaultToken}
      VAULT_ADDR: http://vault:8200
      PLUGIN_MOUNT_PATH: quorum
      PLUGIN_PATH: /vault/plugins
    entrypoint:
    - sh
    - -c
    - |
      ( sleep 2 ; vault-init-dev.sh ) &
       vault server -dev -dev-plugin-dir=/vault/plugins -dev-listen-address="0.0.0.0:8200"
    ports:
    - 8200:8200
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--proxy", "off", "http://vault:8200/v1/sys/health?standbyok=true" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s


  postgres:
    <<: *container-common
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  db-data:
    driver: local

networks:
  deps:
    name: deps_quorum-dev-quickstart
    driver: bridge
