---
version: '3.6'

services:

  blockscout:
    image: consensys/blockscout:e3d5778
    container_name: quorum-dev-quickstart-blockscout
    restart: "no"
    environment:
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@postgres/postgres?ssl=false
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - NETWORK=quickstart
      - CHAIN_ID=1337
      - COIN=ETH
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_TRANSPORT=http
      - ETHEREUM_JSONRPC_HTTP_URL=http://rpcnode:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://rpcnode:8546
    entrypoint:
      - /bin/sh
      - -c
      - |
        cd /opt/app/;
        echo $$MIX_ENV && mix do ecto.create, ecto.migrate; mix phx.server;
    depends_on:
      - postgres
    links:
      - postgres      
    ports:
      - 26000:4000
    networks:
      quickstart:
        ipv4_address: 172.16.239.101

  postgres:
    image: postgres:13.4-alpine
    restart: "on-failure"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
    - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      quickstart:
        ipv4_address: 172.16.239.102

networks:
  quickstart:
    external:
      name: quorum-dev-quickstart

volumes:
  postgres: